// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RuleSimulation.Api.Data;

#nullable disable

namespace RuleSimulation.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260910141514_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RuleSimulation.Api.Domain.RequestRow", b =>
                {
                    b.Property<string>("RequestId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("request_id");

                    b.Property<string>("AccountTier")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("account_tier");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("channel");

                    b.Property<decimal>("DeclaredValue")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("declared_value");

                    b.Property<bool>("FlaggedDuplicate")
                        .HasColumnType("bit")
                        .HasColumnName("flagged_duplicate");

                    b.Property<bool>("HasDocumentation")
                        .HasColumnType("bit")
                        .HasColumnName("has_documentation");

                    b.Property<int>("ItemAgeDays")
                        .HasColumnType("int")
                        .HasColumnName("item_age_days");

                    b.Property<string>("ItemClass")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("item_class");

                    b.Property<string>("ItemCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("item_code");

                    b.Property<int>("PriorRequests90d")
                        .HasColumnType("int")
                        .HasColumnName("prior_requests_90d");

                    b.Property<int>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("quantity");

                    b.Property<string>("RecordedOutcome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("recorded_outcome");

                    b.Property<string>("Region")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("region");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("submitted_at");

                    b.HasKey("RequestId");

                    b.ToTable("Request", (string)null);
                });

            modelBuilder.Entity("RuleSimulation.Api.Domain.Rule", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("ConditionJoin")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<bool>("Enabled")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<long>("RuleSetId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("RuleSetId", "Enabled", "Priority", "DisplayOrder", "Id");

                    b.ToTable("Rule", (string)null);
                });

            modelBuilder.Entity("RuleSimulation.Api.Domain.RuleCondition", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Field")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Operator")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<long>("RuleId")
                        .HasColumnType("bigint");

                    b.Property<int>("Sequence")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("ValuesJson")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.HasKey("Id");

                    b.HasIndex("RuleId", "Sequence")
                        .IsUnique();

                    b.ToTable("RuleCondition", (string)null);
                });

            modelBuilder.Entity("RuleSimulation.Api.Domain.RuleSet", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Enabled")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("RuleSet", (string)null);
                });

            modelBuilder.Entity("RuleSimulation.Api.Domain.Rule", b =>
                {
                    b.HasOne("RuleSimulation.Api.Domain.RuleSet", "RuleSet")
                        .WithMany("Rules")
                        .HasForeignKey("RuleSetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RuleSet");
                });

            modelBuilder.Entity("RuleSimulation.Api.Domain.RuleCondition", b =>
                {
                    b.HasOne("RuleSimulation.Api.Domain.Rule", "Rule")
                        .WithMany("Conditions")
                        .HasForeignKey("RuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rule");
                });

            modelBuilder.Entity("RuleSimulation.Api.Domain.Rule", b =>
                {
                    b.Navigation("Conditions");
                });

            modelBuilder.Entity("RuleSimulation.Api.Domain.RuleSet", b =>
                {
                    b.Navigation("Rules");
                });
#pragma warning restore 612, 618
        }
    }
}
